
name: Run Deploy Pipeline

# As ações ordenadas são em função da branch master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: fifsky/ssh-action@master
        with:
          # O Digital Ocean permite coordenar as ações de deploy e integração contínua. 
          # Neste caso ele entra na pasta do Trabalho Individual e ordena que a cada PR, devem ser
          # feitas as análises
          # Linha 27: deploy do projeto 
          command: |
            cd 
            rm -rf Trabalho-Individual-2020-2
            git clone https://github.com/helenagoulart/Trabalho-Individual-2020-2/
            cd Trabalho-Individual-2020-2
            git checkout ${{ github.event.pull_request.head.ref }}
            docker-compose up --build -d
          host: ${{ secrets.DO_HOST }}
          pass: ${{ secrets.DO_PASSWORD }}